// The `--patch` overlay each child boots with. It is the last layer, so its
// rows win over anything in the child's own profile or home patch; that is
// where everything security-relevant goes.

import { fileURLToPath } from 'node:url'
import { dumpPatch } from './patches.js'

export const HOST_PLUGIN_PATH = fileURLToPath(new URL('../plugin/host.js', import.meta.url))

/** Rows a non-admin child does not load. Each id is a row the shipped web-app
 * bundle mounts; `disabled: true` is the same mechanism the bundle itself uses. */
export const DEFAULT_USER_DISABLED_ROWS = Object.freeze([
  'ui-settings-models', // Settings → Models (+ onboarding cells)
  'ui-settings-plugins', // Settings → Plugins
  'ui-settings-shell', //   plugin cards inside Settings → Plugins
  'ui-settings-agent-loop',
  'ui-settings-subagent',
  'ui-settings-web-search',
  'ui-settings-plugin-inventory',
  'ui-plugin-manager', // sidebar "Plugins" page
  'plugin-manager', // host-side package installs
  'ui-settings-account', // DeepSeek platform account
  'ui-permission', // Settings → General → Permission and the /permission picker
  'ui-sidebar-terminal', // the sidebar terminal is a shell
  'terminal-controller', //   and its host side
  'workspace-files', // file preview reads any path the process can read
  'ui-sidebar-files', //   its sidebar panel
  'ui-sidebar-documentpreview', //   and document preview
  'office-to-pdf', //   which converts host files for that preview
  'directory-picker', // browsing host folders to add workspaces
  'ui-deliverables', // lists files the agent wrote; needs file preview
])

/**
 * @param {{
 *   role: 'admin' | 'user',
 *   handshakeFile: string,
 *   identity?: { name?: string, role: string },
 *   sharedCredentialsFile?: string,
 *   documentsDirectory?: string,
 *   userDisabledRows?: readonly string[],
 *   userTools?: readonly string[],
 *   extraRows?: any[],
 * }} opts
 */
export function buildOverlay(opts) {
  const pluginConfig = {
    role: opts.role,
    handshakeFile: opts.handshakeFile,
    ownsHost: true,
  }
  if (opts.identity) pluginConfig.identity = opts.identity
  if (opts.role === 'user' && opts.userTools) pluginConfig.userTools = [...opts.userTools]

  const rows = [
    { insert: [{ id: 'dsh-ha-ingress-auth', name: HOST_PLUGIN_PATH, config: pluginConfig }] },
  ]
  if (opts.documentsDirectory) {
    // dsh creates the first workspace under the OS "Documents" folder; keep it
    // inside this user's own data directory instead.
    rows.push({
      id: 'workspace-controller',
      name: '@deepseek-ai/dsh-api-workspace-controller',
      config: { documentsDirectory: opts.documentsDirectory },
    })
  }
  if (opts.role === 'admin') {
    if (opts.sharedCredentialsFile) {
      rows.push({
        id: 'credentials',
        name: '@deepseek-ai/dsh-credentials-local',
        config: { path: opts.sharedCredentialsFile },
      })
    }
  } else {
    for (const id of opts.userDisabledRows ?? DEFAULT_USER_DISABLED_ROWS) rows.push({ id, disabled: true })
    // Developer tools stay off for non-admins; the switch is hidden (host.js)
    // and this overlay outranks anything the user saves.
    rows.push({ id: 'ui-settings', name: '@deepseek-ai/dsh-client-ui-settings', config: { enabled: false } })
  }
  for (const row of opts.extraRows ?? []) rows.push(row)
  return dumpPatch(rows, '# Generated by the dsh-ha-ingress-auth gateway for each child launch.\n')
}
